steps:
- task: Gradle@2
  displayName: Build
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '--no-daemon'
    tasks: 'check'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'


