steps:
- task: Gradle@2
  displayName: Build
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '--no-daemon --scan'
    tasks: 'testcontainers:check'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'


